class AppError extends Error {
  // Error is built in error class in node js

  constructor(message, statusCode) {
    super(message); // call super class constructor with super with the arg that super class constructor accpets i.e. message

    this.statusCode = statusCode;
    this.status = `${statusCode}`.startsWith('4') ? 'fail' : 'error';

    this.isOperational = true; // because all the errors from this class would be operational...

    Error.captureStackTrace(this, this.constructor); // this.constructor = app Error class.
  }
}

export default AppError;

// operational erros => errors that are generated by the client side like invalid data error, missing field error etc.
// programming errors ==> errors that are generated in our code and that has nothing to do with the client side are called programming errors.
